# Generated by Django 5.0.1 on 2025-12-20 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Supported formats: CSV, TXT, JSON, HTML', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt', 'json', 'html'])])),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('txt', 'TXT'), ('json', 'JSON'), ('html', 'HTML')], help_text='File extension', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
